/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicTermsAndConditionsRouteImport } from './routes/_public/terms-and-conditions'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicDisclaimerRouteImport } from './routes/_public/disclaimer'
import { Route as PrivateSettingsRouteImport } from './routes/_private/settings'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateNotificationsRouteImport } from './routes/_private/notifications'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as PrivateIdeaIndexRouteImport } from './routes/_private/idea/index'
import { Route as PrivateIdeaAddRouteImport } from './routes/_private/idea/add'
import { Route as PrivateIdeaIdeaIdIndexRouteImport } from './routes/_private/idea/$ideaId/index'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsAndConditionsRoute =
  PublicTermsAndConditionsRouteImport.update({
    id: '/_public/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/_public/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDisclaimerRoute = PublicDisclaimerRouteImport.update({
  id: '/_public/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateNotificationsRoute = PrivateNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PrivateIdeaIndexRoute = PrivateIdeaIndexRouteImport.update({
  id: '/idea/',
  path: '/idea/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateIdeaAddRoute = PrivateIdeaAddRouteImport.update({
  id: '/idea/add',
  path: '/idea/add',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateIdeaIdeaIdIndexRoute = PrivateIdeaIdeaIdIndexRouteImport.update({
  id: '/idea/$ideaId/',
  path: '/idea/$ideaId/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/notifications': typeof PrivateNotificationsRoute
  '/profile': typeof PrivateProfileRoute
  '/settings': typeof PrivateSettingsRoute
  '/disclaimer': typeof PublicDisclaimerRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-and-conditions': typeof PublicTermsAndConditionsRoute
  '/idea/add': typeof PrivateIdeaAddRoute
  '/idea': typeof PrivateIdeaIndexRoute
  '/idea/$ideaId': typeof PrivateIdeaIdeaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/notifications': typeof PrivateNotificationsRoute
  '/profile': typeof PrivateProfileRoute
  '/settings': typeof PrivateSettingsRoute
  '/disclaimer': typeof PublicDisclaimerRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-and-conditions': typeof PublicTermsAndConditionsRoute
  '/idea/add': typeof PrivateIdeaAddRoute
  '/idea': typeof PrivateIdeaIndexRoute
  '/idea/$ideaId': typeof PrivateIdeaIdeaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/notifications': typeof PrivateNotificationsRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/settings': typeof PrivateSettingsRoute
  '/_public/disclaimer': typeof PublicDisclaimerRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/terms-and-conditions': typeof PublicTermsAndConditionsRoute
  '/_private/idea/add': typeof PrivateIdeaAddRoute
  '/_private/idea/': typeof PrivateIdeaIndexRoute
  '/_private/idea/$ideaId/': typeof PrivateIdeaIdeaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/disclaimer'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/idea/add'
    | '/idea'
    | '/idea/$ideaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/disclaimer'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/idea/add'
    | '/idea'
    | '/idea/$ideaId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_private'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_private/dashboard'
    | '/_private/notifications'
    | '/_private/profile'
    | '/_private/settings'
    | '/_public/disclaimer'
    | '/_public/privacy-policy'
    | '/_public/terms-and-conditions'
    | '/_private/idea/add'
    | '/_private/idea/'
    | '/_private/idea/$ideaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicDisclaimerRoute: typeof PublicDisclaimerRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicTermsAndConditionsRoute: typeof PublicTermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms-and-conditions': {
      id: '/_public/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof PublicTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/disclaimer': {
      id: '/_public/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof PublicDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/notifications': {
      id: '/_private/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof PrivateNotificationsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_private/idea/': {
      id: '/_private/idea/'
      path: '/idea'
      fullPath: '/idea'
      preLoaderRoute: typeof PrivateIdeaIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/idea/add': {
      id: '/_private/idea/add'
      path: '/idea/add'
      fullPath: '/idea/add'
      preLoaderRoute: typeof PrivateIdeaAddRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/idea/$ideaId/': {
      id: '/_private/idea/$ideaId/'
      path: '/idea/$ideaId'
      fullPath: '/idea/$ideaId'
      preLoaderRoute: typeof PrivateIdeaIdeaIdIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateRouteRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateNotificationsRoute: typeof PrivateNotificationsRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateSettingsRoute: typeof PrivateSettingsRoute
  PrivateIdeaAddRoute: typeof PrivateIdeaAddRoute
  PrivateIdeaIndexRoute: typeof PrivateIdeaIndexRoute
  PrivateIdeaIdeaIdIndexRoute: typeof PrivateIdeaIdeaIdIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateNotificationsRoute: PrivateNotificationsRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateSettingsRoute: PrivateSettingsRoute,
  PrivateIdeaAddRoute: PrivateIdeaAddRoute,
  PrivateIdeaIndexRoute: PrivateIdeaIndexRoute,
  PrivateIdeaIdeaIdIndexRoute: PrivateIdeaIdeaIdIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicDisclaimerRoute: PublicDisclaimerRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicTermsAndConditionsRoute: PublicTermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
